---
- hosts: aws

# for first time install python use this command:
# ansible aws -i script/hosts --sudo -m raw -a "apt-get install -y python python-simplejson"

  tasks:
  - name: Install required packages
    action: >
      {{ ansible_pkg_mgr }} name={{ item }} state=present update_cache=yes
    become: true
    with_items:
      - python
      - python-pip
      - python-zmq
      - python-pygame
      - chrony

  - name: Set timezone
    shell: timedatectl set-timezone Europe/Amsterdam
    become: true

  - name: Copy over the chrony configuration
    template: src=./chrony.conf dest=/etc/chrony/chrony.conf
    become: true
    notify:
    - Restart chrony
 
  - name: Make sure chrony is stopped
    service: name=chrony state=stopped enabled=yes
    become: true
 
  - name: Sync time initialy
    shell: chronyd -q
    become: true

  - name: Make sure chrony is started up
    service: name=chrony state=started enabled=yes
    become: true

  - name: Sync hwclock
    shell: hwclock -w
    become: true

  - name: Get dragonsarena from Github
    git:
      repo: 'https://github.com/riftadi/dragonsarena.git'
      dest: /home/ubuntu/dragonsarena

  handlers:
  - name: Restart chrony
    service: name=chrony state=restarted
    become: true
